# Generated by Django 3.0.6 on 2020-07-10 21:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20200408_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('status', models.NullBooleanField(default=True)),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('product', models.ManyToManyField(blank=True, null=True, to='hrm.Product')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrm.CompanyType')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrm.CompanyType'),
        ),
    ]
